### ISSUE TITLE
[FE] material-ui-picker 사용시 에러 발생

### ISSUE THREAD

**Issue by yellow2041** [boostcamp-2020/Project07-A-RealTime-Seat-Reservation-System#10]
- @data-io 에서 특정 모듈을 찾을 수 없다고 나옴
- 캘린더 직접 구현도 고려?

**Comment by swlee60** [comment]
@yellow2041 
캘린더는 후순위로 하시는건 어떨까요?

**Comment by yellow2041** [comment]
@swlee60 우선 좌석선택 페이지를 완성한 후 구현을 고려해보겠습니다!

**Comment by yellow2041** [comment]
React-calendar를 사용하여 해결하였습니다.
